# Generated by Django 5.1.15 on 2026-09-20 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_departmentcatalog_alter_department_options_and_more'),
        ('members', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='departments.department'),
        ),
        migrations.AddField(
            model_name='member',
            name='ecclesial_function',
            field=models.CharField(choices=[('PASTEUR', 'Pasteur'), ('ANCIEN', 'Ancien'), ('DIACRE', 'Diacre'), ('EVANGELISTE', 'Évangéliste'), ('DOCTEUR', 'Docteur'), ('PROPHETE', 'Prophète'), ('BERGER', 'Berger'), ('RESPONSABLE_DEPT', 'Responsable de Département'), ('ADJOINT_DEPT', 'Adjoint de Département'), ('OUVRIER', 'Ouvrier'), ('MEMBRE', 'Membre')], default='MEMBRE', max_length=30),
        ),
    ]
