# Generated by Django 5.1.15 on 2026-09-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('campus_type', models.CharField(choices=[('HQ', 'Siège Mondial'), ('EXTENSION', 'Extension'), ('FOYER', "Foyer d'Implantation")], default='EXTENSION', max_length=20)),
                ('country', models.CharField(default='Congo', max_length=60)),
                ('city', models.CharField(default='Pointe-Noire', max_length=60)),
                ('enable_brigades', models.BooleanField(default=True)),
                ('enable_patrimoine', models.BooleanField(default=True)),
                ('enable_finances', models.BooleanField(default=True)),
                ('enable_ai_voice', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
