# Generated by Django 5.1.15 on 2026-09-20 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuses', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campus',
            options={'ordering': ['name'], 'verbose_name': 'Église / Extension', 'verbose_name_plural': 'Églises & Extensions'},
        ),
        migrations.AddField(
            model_name='campus',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='campus',
            name='code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_extensions', to='campuses.campus'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='campus_type',
            field=models.CharField(choices=[('HQ', 'Église Mère (Siège Mondial)'), ('EXTENSION', 'Extension'), ('FOYER', "Foyer d'Implantation")], default='EXTENSION', max_length=20),
        ),
        migrations.AlterField(
            model_name='campus',
            name='lead_pastor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_campuses', to=settings.AUTH_USER_MODEL),
        ),
    ]
