# Generated by Django 5.1.15 on 2026-09-20 23:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuses', '0003_alter_campus_options_campus_address_campus_code_and_more'),
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='Users', help_text="Nom de l'icône Lucide", max_length=50)),
                ('is_default', models.BooleanField(default=True, help_text="Proposé par défaut à l'activation d'une Église")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Catalogue de Structure',
                'verbose_name_plural': 'Catalogue des Structures',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': "Département d'Église", 'verbose_name_plural': "Départements d'Église"},
        ),
        migrations.AddField(
            model_name='department',
            name='admin',
            field=models.ForeignKey(blank=True, help_text='Administrateur titulaire du département', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='department',
            name='deputy',
            field=models.ForeignKey(blank=True, help_text='Adjoint du département', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deputy_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='icon',
            field=models.CharField(default='Users', max_length=50),
        ),
        migrations.AddField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='department',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('campus', 'name')},
        ),
        migrations.AddField(
            model_name='department',
            name='catalog_item',
            field=models.ForeignKey(blank=True, help_text='Référence au catalogue global (si créé depuis le catalogue)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_departments', to='departments.departmentcatalog'),
        ),
    ]
