# Generated by Django 5.1.15 on 2026-09-10 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuses', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='campuses.campus'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_SUPER_ADMIN', 'Super Super Admin'), ('SUPER_ADMIN_CAMPUS', 'Super Admin Campus'), ('GESTIONNAIRE_CAISSE', 'Gestionnaire de Caisse'), ('RESPONSABLE_PATRIMOINE', 'Responsable Patrimoine'), ('CHEF_BRIGADE', 'Chef de Brigade'), ('RESPONSABLE_DEPARTEMENT', 'Responsable de Département'), ('FIDELE', 'Fidèle')], default='FIDELE', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
