# Generated by Django 5.1.15 on 2026-09-20 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar_user_campus_user_role_user_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='delegated_permissions',
            field=models.JSONField(blank=True, default=list, help_text="Liste des permissions accordées à cet adjoint (ex: ['voir', 'valider', 'creer'])."),
        ),
        migrations.AddField(
            model_name='user',
            name='deputy_of',
            field=models.ForeignKey(blank=True, help_text="Le responsable titulaire dont cet utilisateur est l'adjoint.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deputies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='ecclesial_function',
            field=models.CharField(choices=[('APOTRE', 'Apôtre'), ('PASTEUR', 'Pasteur'), ('ANCIEN', 'Ancien'), ('DIACRE', 'Diacre'), ('EVANGELISTE', 'Évangéliste'), ('DOCTEUR', 'Docteur'), ('PROPHETE', 'Prophète'), ('BERGER', 'Berger'), ('RESPONSABLE', 'Responsable de Département'), ('ADJOINT_DEPT', 'Adjoint de Département'), ('OUVRIER', 'Ouvrier'), ('FIDELE', 'Fidèle / Membre')], default='FIDELE', max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deputy',
            field=models.BooleanField(default=False, help_text="Indique si cet utilisateur agit comme adjoint d'un titulaire."),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_SUPER_ADMIN', 'Super Super Admin (Global HSC)'), ('SUPER_ADMIN', 'Super Admin (Église / Extension)'), ('ADMIN_DEPT', 'Admin (Département / Structure)'), ('ADJOINT', 'Adjoint (Délégué)'), ('MEMBRE', 'Membre / Fidèle')], default='MEMBRE', max_length=30),
        ),
    ]
