# Generated by Django 5.1.15 on 2026-09-02 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campuses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé (Par Pasteur)'), ('DISBURSED', 'Décaissé (Par Trésorier)'), ('REJECTED', 'Rejeté')], max_length=20)),
                ('new_status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé (Par Pasteur)'), ('DISBURSED', 'Décaissé (Par Trésorier)'), ('REJECTED', 'Rejeté')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('register_type', models.CharField(choices=[('CASH', 'Caisse Espèces'), ('BANK', 'Compte Bancaire'), ('MOBILE_MONEY', 'Mobile Money (Airtel/MoMo)')], max_length=20)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='campuses.campus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé (Par Pasteur)'), ('DISBURSED', 'Décaissé (Par Trésorier)'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=20)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='vouchers/receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='campuses.campus')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='finances.register')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
