# Generated by Django 5.1.15 on 2026-09-02 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campuses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('SERVICES', 'Services Professionnels'), ('TRADE', 'Commerce et Vente'), ('TECH', 'Informatique & Tech'), ('HEALTH', 'Santé & Bien-être'), ('ART', 'Arts & Créativité'), ('OTHER', 'Autre')], max_length=20)),
                ('description', models.TextField()),
                ('whatsapp_number', models.CharField(max_length=30)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='campuses.campus')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
