# Generated by Django 5.1.15 on 2026-09-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('VOICE_MEMO', 'Mémo Vocal (Whisper)'), ('OCR_ATTENDANCE', 'Feuille de Présence (Vision)')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSING', 'En cours de traitement'), ('SUCCESS', 'Succès'), ('FAILED', 'Échec')], default='PENDING', max_length=20)),
                ('source_file', models.FileField(upload_to='ai_engine/sources/')),
                ('extracted_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
