# Generated by Django 5.1.15 on 2026-09-02 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_engine', '0001_initial'),
        ('campuses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ailog',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='campuses.campus'),
        ),
    ]
