# Generated by Django 5.1.15 on 2026-09-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssimilationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.CharField(choices=[('CONTACT', 'Contact Initial'), ('M1', 'Cours M1'), ('M2', 'Cours M2'), ('BAPTISM', 'Préparation Baptême'), ('INTEGRATED', 'Intégré')], default='CONTACT', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_advanced_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BaptismInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Programmé'), ('APPROVED', 'Approuvé pour Baptême'), ('POSTPONED', 'Ajourné')], default='SCHEDULED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('scheduled_baptism_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.CharField(choices=[('M1', 'Module 1'), ('M2', 'Module 2')], max_length=10)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
