# Generated by Django 5.1.15 on 2026-09-02 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assimilation', '0001_initial'),
        ('campuses', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assimilationprofile',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assimilation_profile', to='members.member'),
        ),
        migrations.AddField(
            model_name='baptisminterview',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='campuses.campus'),
        ),
        migrations.AddField(
            model_name='baptisminterview',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baptism_interviews', to='members.member'),
        ),
    ]
